version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: ./gradlew test
      - run:
          name: "Run integration tests"
          command: ./gradlew integrationTest
      - run:
          name: "Generate test coverage report"
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: build/reports/tests/test
          destination: test-results
      - store_artifacts:
          path: build/reports/jacoco/test
          destination: coverage-report
      - store_test_results:
          path: build/test-results/test

workflows:
  test-oriented-workflow:
    jobs:
      - test